// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.14.0
// source: proto/agentrpc.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//*
// CloneRequest is the request message to invoke MySQL CLONE command.
type CloneRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Host         string `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`                                     // host is the donor host in the own cluster
	Port         int32  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`                                    // port is the port number where the donor host
	User         string `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`                                     // user is the MySQL user who has BACKUP_ADMIN privilege in the donor host.
	Password     string `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`                             // password for the above user.
	InitUser     string `protobuf:"bytes,5,opt,name=init_user,json=initUser,proto3" json:"init_user,omitempty"`             // localhost user to initialize cloned database for MOCO.
	InitPassword string `protobuf:"bytes,6,opt,name=init_password,json=initPassword,proto3" json:"init_password,omitempty"` // password for init_user.
}

func (x *CloneRequest) Reset() {
	*x = CloneRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_agentrpc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CloneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloneRequest) ProtoMessage() {}

func (x *CloneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agentrpc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloneRequest.ProtoReflect.Descriptor instead.
func (*CloneRequest) Descriptor() ([]byte, []int) {
	return file_proto_agentrpc_proto_rawDescGZIP(), []int{0}
}

func (x *CloneRequest) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *CloneRequest) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *CloneRequest) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *CloneRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *CloneRequest) GetInitUser() string {
	if x != nil {
		return x.InitUser
	}
	return ""
}

func (x *CloneRequest) GetInitPassword() string {
	if x != nil {
		return x.InitPassword
	}
	return ""
}

//*
// CloneResponse is the response message of Clone.
type CloneResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CloneResponse) Reset() {
	*x = CloneResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_agentrpc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CloneResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloneResponse) ProtoMessage() {}

func (x *CloneResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agentrpc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloneResponse.ProtoReflect.Descriptor instead.
func (*CloneResponse) Descriptor() ([]byte, []int) {
	return file_proto_agentrpc_proto_rawDescGZIP(), []int{1}
}

var File_proto_agentrpc_proto protoreflect.FileDescriptor

var file_proto_agentrpc_proto_rawDesc = []byte{
	0x0a, 0x14, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x72, 0x70, 0x63,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x6d, 0x6f, 0x63, 0x6f, 0x22, 0xa8, 0x01, 0x0a,
	0x0c, 0x43, 0x6c, 0x6f, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x68, 0x6f, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x6f, 0x73,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x04, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73,
	0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73,
	0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x6e, 0x69, 0x74, 0x5f, 0x75, 0x73,
	0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x69, 0x6e, 0x69, 0x74, 0x55, 0x73,
	0x65, 0x72, 0x12, 0x23, 0x0a, 0x0d, 0x69, 0x6e, 0x69, 0x74, 0x5f, 0x70, 0x61, 0x73, 0x73, 0x77,
	0x6f, 0x72, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x69, 0x6e, 0x69, 0x74, 0x50,
	0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x0f, 0x0a, 0x0d, 0x43, 0x6c, 0x6f, 0x6e, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0x39, 0x0a, 0x05, 0x41, 0x67, 0x65, 0x6e,
	0x74, 0x12, 0x30, 0x0a, 0x05, 0x43, 0x6c, 0x6f, 0x6e, 0x65, 0x12, 0x12, 0x2e, 0x6d, 0x6f, 0x63,
	0x6f, 0x2e, 0x43, 0x6c, 0x6f, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13,
	0x2e, 0x6d, 0x6f, 0x63, 0x6f, 0x2e, 0x43, 0x6c, 0x6f, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x42, 0x27, 0x5a, 0x25, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x63, 0x79, 0x62, 0x6f, 0x7a, 0x75, 0x2d, 0x67, 0x6f, 0x2f, 0x6d, 0x6f, 0x63, 0x6f,
	0x2d, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_agentrpc_proto_rawDescOnce sync.Once
	file_proto_agentrpc_proto_rawDescData = file_proto_agentrpc_proto_rawDesc
)

func file_proto_agentrpc_proto_rawDescGZIP() []byte {
	file_proto_agentrpc_proto_rawDescOnce.Do(func() {
		file_proto_agentrpc_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_agentrpc_proto_rawDescData)
	})
	return file_proto_agentrpc_proto_rawDescData
}

var file_proto_agentrpc_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_agentrpc_proto_goTypes = []interface{}{
	(*CloneRequest)(nil),  // 0: moco.CloneRequest
	(*CloneResponse)(nil), // 1: moco.CloneResponse
}
var file_proto_agentrpc_proto_depIdxs = []int32{
	0, // 0: moco.Agent.Clone:input_type -> moco.CloneRequest
	1, // 1: moco.Agent.Clone:output_type -> moco.CloneResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_agentrpc_proto_init() }
func file_proto_agentrpc_proto_init() {
	if File_proto_agentrpc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_agentrpc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CloneRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_agentrpc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CloneResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_agentrpc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_agentrpc_proto_goTypes,
		DependencyIndexes: file_proto_agentrpc_proto_depIdxs,
		MessageInfos:      file_proto_agentrpc_proto_msgTypes,
	}.Build()
	File_proto_agentrpc_proto = out.File
	file_proto_agentrpc_proto_rawDesc = nil
	file_proto_agentrpc_proto_goTypes = nil
	file_proto_agentrpc_proto_depIdxs = nil
}
