// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/agentrpc.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// *
// CloneRequest is the request message to invoke MySQL CLONE command.
type CloneRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`                                     // host is the donor host in the own cluster
	Port          int32                  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`                                    // port is the port number where the donor host
	User          string                 `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`                                     // user is the MySQL user who has BACKUP_ADMIN privilege in the donor host.
	Password      string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`                             // password for the above user.
	InitUser      string                 `protobuf:"bytes,5,opt,name=init_user,json=initUser,proto3" json:"init_user,omitempty"`             // localhost user to initialize cloned database for MOCO.
	InitPassword  string                 `protobuf:"bytes,6,opt,name=init_password,json=initPassword,proto3" json:"init_password,omitempty"` // password for init_user.
	BootTimeout   *durationpb.Duration   `protobuf:"bytes,7,opt,name=boot_timeout,json=bootTimeout,proto3" json:"boot_timeout,omitempty"`    // wait up to this duration for mysqld to boot after clone.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloneRequest) Reset() {
	*x = CloneRequest{}
	mi := &file_proto_agentrpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloneRequest) ProtoMessage() {}

func (x *CloneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agentrpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloneRequest.ProtoReflect.Descriptor instead.
func (*CloneRequest) Descriptor() ([]byte, []int) {
	return file_proto_agentrpc_proto_rawDescGZIP(), []int{0}
}

func (x *CloneRequest) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *CloneRequest) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *CloneRequest) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *CloneRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *CloneRequest) GetInitUser() string {
	if x != nil {
		return x.InitUser
	}
	return ""
}

func (x *CloneRequest) GetInitPassword() string {
	if x != nil {
		return x.InitPassword
	}
	return ""
}

func (x *CloneRequest) GetBootTimeout() *durationpb.Duration {
	if x != nil {
		return x.BootTimeout
	}
	return nil
}

// *
// CloneResponse is the response message of Clone.
type CloneResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloneResponse) Reset() {
	*x = CloneResponse{}
	mi := &file_proto_agentrpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloneResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloneResponse) ProtoMessage() {}

func (x *CloneResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agentrpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloneResponse.ProtoReflect.Descriptor instead.
func (*CloneResponse) Descriptor() ([]byte, []int) {
	return file_proto_agentrpc_proto_rawDescGZIP(), []int{1}
}

var File_proto_agentrpc_proto protoreflect.FileDescriptor

const file_proto_agentrpc_proto_rawDesc = "" +
	"\n" +
	"\x14proto/agentrpc.proto\x12\x04moco\x1a\x1egoogle/protobuf/duration.proto\"\xe6\x01\n" +
	"\fCloneRequest\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x05R\x04port\x12\x12\n" +
	"\x04user\x18\x03 \x01(\tR\x04user\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\x12\x1b\n" +
	"\tinit_user\x18\x05 \x01(\tR\binitUser\x12#\n" +
	"\rinit_password\x18\x06 \x01(\tR\finitPassword\x12<\n" +
	"\fboot_timeout\x18\a \x01(\v2\x19.google.protobuf.DurationR\vbootTimeout\"\x0f\n" +
	"\rCloneResponse29\n" +
	"\x05Agent\x120\n" +
	"\x05Clone\x12\x12.moco.CloneRequest\x1a\x13.moco.CloneResponseB'Z%github.com/cybozu-go/moco-agent/protob\x06proto3"

var (
	file_proto_agentrpc_proto_rawDescOnce sync.Once
	file_proto_agentrpc_proto_rawDescData []byte
)

func file_proto_agentrpc_proto_rawDescGZIP() []byte {
	file_proto_agentrpc_proto_rawDescOnce.Do(func() {
		file_proto_agentrpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_agentrpc_proto_rawDesc), len(file_proto_agentrpc_proto_rawDesc)))
	})
	return file_proto_agentrpc_proto_rawDescData
}

var file_proto_agentrpc_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_agentrpc_proto_goTypes = []any{
	(*CloneRequest)(nil),        // 0: moco.CloneRequest
	(*CloneResponse)(nil),       // 1: moco.CloneResponse
	(*durationpb.Duration)(nil), // 2: google.protobuf.Duration
}
var file_proto_agentrpc_proto_depIdxs = []int32{
	2, // 0: moco.CloneRequest.boot_timeout:type_name -> google.protobuf.Duration
	0, // 1: moco.Agent.Clone:input_type -> moco.CloneRequest
	1, // 2: moco.Agent.Clone:output_type -> moco.CloneResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_agentrpc_proto_init() }
func file_proto_agentrpc_proto_init() {
	if File_proto_agentrpc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_agentrpc_proto_rawDesc), len(file_proto_agentrpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_agentrpc_proto_goTypes,
		DependencyIndexes: file_proto_agentrpc_proto_depIdxs,
		MessageInfos:      file_proto_agentrpc_proto_msgTypes,
	}.Build()
	File_proto_agentrpc_proto = out.File
	file_proto_agentrpc_proto_goTypes = nil
	file_proto_agentrpc_proto_depIdxs = nil
}
