name: CI
on:
  pull_request:
  push:
    branches:
    - 'main'
env:
  cache-version: 1
jobs:
  validation:
    name: Validation
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version-file: go.mod
    - name: Cache Tools
      id: cache-tools
      uses: actions/cache@v3
      with:
        path: |
          bin
          include
        key: cache-${{ env.cache-version }}-${{ hashFiles('go.mod') }}-${{ hashFiles('Makefile') }}
    - run: make setup
      if: steps.cache-tools.outputs.cache-hit != 'true'
    - run: make validate
    - run: make check-generate
  build:
    name: build
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version-file: go.mod
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2
    - run: docker buildx build --load -t moco-agent:dev .
  test:
    name: Small Tests
    strategy:
      matrix:
        mysql-version: ["8.0.18", "8.0.25", "8.0.26", "8.0.27", "8.0.28"]
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version-file: go.mod
    - run: make test MYSQL_VERSION=${{ matrix.mysql-version }}
