name: CI
on:
  pull_request:
  push:
    branches:
      - 'main'
env:
  go-version: 1.16
jobs:
  validation:
    name: Validation
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ env.go-version }}
      - name: Cache Tools
        id: cache-tools
        uses: actions/cache@v2
        with:
          path: |
            bin
          key: cache-${{ env.cache-version }}-go-${{ env.go-version }}-${{ hashFiles('Makefile') }}
      - run: make setup
        if: steps.cache-tools.outputs.cache-hit != 'true'
      - run: make validate
  test:
    name: Small Tests
    strategy:
      matrix:
        mysql-version: ["8.0.18", "8.0.20"]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ env.go-version }}
      - run: make test MYSQL_VERSION=${{ matrix.mysql-version }}
