name: Release
on:
  push:
    tags:
    - 'v*'
env:
  go-version: 1.16
jobs:
  release:
    name: Release on GitHub
    needs: image
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ env.go-version }}
      - run: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 make build/moco-agent
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            See [CHANGELOG.md](./CHANGELOG.md) for details.
          draft: false
          prerelease: ${{ contains(github.ref, '-') }}
      - name: Upload Agent
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/moco-agent
          asset_name: moco-agent
          asset_content_type: application/octet-stream
      - name: Upload Agent RPC definition
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./proto/agentrpc.proto
          asset_name: agentrpc.proto
          asset_content_type: application/octet-stream
  image:
    name: Push Container Image
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Login to ghcr.io
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
      - run: docker build -t ghcr.io/cybozu-go/moco-agent:${GITHUB_REF#refs/tags/v} .
      - run: docker push ghcr.io/cybozu-go/moco-agent:${GITHUB_REF#refs/tags/v}
