name: Release
on:
  push:
    tags:
    - 'v*'
jobs:
  release:
    name: Release on GitHub
    needs: image
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
      - run: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 make build/moco-agent
      - name: Create Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          VERSION=${GITHUB_REF#refs/tags/} # Don't remove "v" prefix.
          if echo ${VERSION} | grep -q -e '-'; then PRERELEASE_FLAG=-p; fi
          gh release create $VERSION $PRERELEASE_FLAG \
            -t "Release $VERSION"  \
            -n "See [CHANGELOG.md](./CHANGELOG.md) for details."
          gh release upload $VERSION ./build/moco-agent ./proto/agentrpc.proto
  image:
    name: Push Container Image
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Login to ghcr.io
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
      - run: docker build -t ghcr.io/cybozu-go/moco-agent:${GITHUB_REF#refs/tags/v} .
      - run: docker push ghcr.io/cybozu-go/moco-agent:${GITHUB_REF#refs/tags/v}
